name = "shamus-li"
compatibility_date = "2026-05-14"
pages_build_output_dir = "dist"

[vars]
CLOUDFLARE_ACCOUNT_ID = "2f56e0cba9c55090b02f5948da4ff347"
REDIRECT_HOSTNAME = "shamus.li"
REDIRECT_LIST_NAME = "pages_to_custom_domain"
